compute_environment: LOCAL_MACHINE
debug: true
distributed_type: 'NO'
dynamo_backend: 'NO'
gpu_ids: '0'
machine_rank: 0
main_process_ip: 172.16.0.105
main_process_port: 12345
main_training_function: main
megatron_lm_config: {}
mixed_precision: bf16
num_machines: 1  # Set to 1 machine
num_processes: 1  # Set to 1 process
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

